#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Python on August 20, 2021 at 12:23:02.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[412];
extern c_float ldata[724];
extern c_float udata[724];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[412];
extern c_float Dinvscaling[412];
extern c_float Escaling[724];
extern c_float Einvscaling[724];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[1136];
extern c_int linsys_solver_P[1136];
extern c_float linsys_solver_bp[1136];
extern c_float linsys_solver_sol[1136];
extern c_float linsys_solver_rho_inv_vec[724];
extern c_int linsys_solver_Pdiag_idx[204];
extern csc linsys_solver_KKT;
extern c_int linsys_solver_PtoKKT[204];
extern c_int linsys_solver_AtoKKT[5524];
extern c_int linsys_solver_rhotoKKT[724];
extern QDLDL_float linsys_solver_D[1136];
extern QDLDL_int linsys_solver_etree[1136];
extern QDLDL_int linsys_solver_Lnz[1136];
extern QDLDL_int   linsys_solver_iwork[3408];
extern QDLDL_bool  linsys_solver_bwork[1136];
extern QDLDL_float linsys_solver_fwork[1136];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[412];
extern c_float ysolution[724];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[724];
extern c_float work_rho_inv_vec[724];
extern c_int work_constr_type[724];
extern c_float work_x[412];
extern c_float work_y[724];
extern c_float work_z[724];
extern c_float work_xz_tilde[1136];
extern c_float work_x_prev[412];
extern c_float work_z_prev[724];
extern c_float work_Ax[724];
extern c_float work_Px[412];
extern c_float work_Aty[412];
extern c_float work_delta_y[724];
extern c_float work_Atdelta_y[412];
extern c_float work_delta_x[412];
extern c_float work_Pdelta_x[412];
extern c_float work_Adelta_x[724];
extern c_float work_D_temp[412];
extern c_float work_D_temp_A[412];
extern c_float work_E_temp[724];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
