#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Python on August 24, 2021 at 13:46:16.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[568];
extern c_float ldata[880];
extern c_float udata[880];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[568];
extern c_float Dinvscaling[568];
extern c_float Escaling[880];
extern c_float Einvscaling[880];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[1448];
extern c_int linsys_solver_P[1448];
extern c_float linsys_solver_bp[1448];
extern c_float linsys_solver_sol[1448];
extern c_float linsys_solver_rho_inv_vec[880];
extern c_int linsys_solver_Pdiag_idx[218];
extern csc linsys_solver_KKT;
extern c_int linsys_solver_PtoKKT[371];
extern c_int linsys_solver_AtoKKT[10780];
extern c_int linsys_solver_rhotoKKT[880];
extern QDLDL_float linsys_solver_D[1448];
extern QDLDL_int linsys_solver_etree[1448];
extern QDLDL_int linsys_solver_Lnz[1448];
extern QDLDL_int   linsys_solver_iwork[4344];
extern QDLDL_bool  linsys_solver_bwork[1448];
extern QDLDL_float linsys_solver_fwork[1448];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[568];
extern c_float ysolution[880];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[880];
extern c_float work_rho_inv_vec[880];
extern c_int work_constr_type[880];
extern c_float work_x[568];
extern c_float work_y[880];
extern c_float work_z[880];
extern c_float work_xz_tilde[1448];
extern c_float work_x_prev[568];
extern c_float work_z_prev[880];
extern c_float work_Ax[880];
extern c_float work_Px[568];
extern c_float work_Aty[568];
extern c_float work_delta_y[880];
extern c_float work_Atdelta_y[568];
extern c_float work_delta_x[568];
extern c_float work_Pdelta_x[568];
extern c_float work_Adelta_x[880];
extern c_float work_D_temp[568];
extern c_float work_D_temp_A[568];
extern c_float work_E_temp[880];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
