#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Python on August 20, 2021 at 20:12:06.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[492];
extern c_float ldata[864];
extern c_float udata[864];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[492];
extern c_float Dinvscaling[492];
extern c_float Escaling[864];
extern c_float Einvscaling[864];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[1356];
extern c_int linsys_solver_P[1356];
extern c_float linsys_solver_bp[1356];
extern c_float linsys_solver_sol[1356];
extern c_float linsys_solver_rho_inv_vec[864];
extern c_int linsys_solver_Pdiag_idx[244];
extern csc linsys_solver_KKT;
extern c_int linsys_solver_PtoKKT[244];
extern c_int linsys_solver_AtoKKT[6624];
extern c_int linsys_solver_rhotoKKT[864];
extern QDLDL_float linsys_solver_D[1356];
extern QDLDL_int linsys_solver_etree[1356];
extern QDLDL_int linsys_solver_Lnz[1356];
extern QDLDL_int   linsys_solver_iwork[4068];
extern QDLDL_bool  linsys_solver_bwork[1356];
extern QDLDL_float linsys_solver_fwork[1356];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[492];
extern c_float ysolution[864];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[864];
extern c_float work_rho_inv_vec[864];
extern c_int work_constr_type[864];
extern c_float work_x[492];
extern c_float work_y[864];
extern c_float work_z[864];
extern c_float work_xz_tilde[1356];
extern c_float work_x_prev[492];
extern c_float work_z_prev[864];
extern c_float work_Ax[864];
extern c_float work_Px[492];
extern c_float work_Aty[492];
extern c_float work_delta_y[864];
extern c_float work_Atdelta_y[492];
extern c_float work_delta_x[492];
extern c_float work_Pdelta_x[492];
extern c_float work_Adelta_x[864];
extern c_float work_D_temp[492];
extern c_float work_D_temp_A[492];
extern c_float work_E_temp[864];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
