#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Python on August 25, 2021 at 16:19:41.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[698];
extern c_float ldata[1010];
extern c_float udata[1010];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[698];
extern c_float Dinvscaling[698];
extern c_float Escaling[1010];
extern c_float Einvscaling[1010];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[1708];
extern c_int linsys_solver_P[1708];
extern c_float linsys_solver_bp[1708];
extern c_float linsys_solver_sol[1708];
extern c_float linsys_solver_rho_inv_vec[1010];
extern c_int linsys_solver_Pdiag_idx[204];
extern csc linsys_solver_KKT;
extern c_int linsys_solver_PtoKKT[204];
extern c_int linsys_solver_AtoKKT[16535];
extern c_int linsys_solver_rhotoKKT[1010];
extern QDLDL_float linsys_solver_D[1708];
extern QDLDL_int linsys_solver_etree[1708];
extern QDLDL_int linsys_solver_Lnz[1708];
extern QDLDL_int   linsys_solver_iwork[5124];
extern QDLDL_bool  linsys_solver_bwork[1708];
extern QDLDL_float linsys_solver_fwork[1708];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[698];
extern c_float ysolution[1010];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[1010];
extern c_float work_rho_inv_vec[1010];
extern c_int work_constr_type[1010];
extern c_float work_x[698];
extern c_float work_y[1010];
extern c_float work_z[1010];
extern c_float work_xz_tilde[1708];
extern c_float work_x_prev[698];
extern c_float work_z_prev[1010];
extern c_float work_Ax[1010];
extern c_float work_Px[698];
extern c_float work_Aty[698];
extern c_float work_delta_y[1010];
extern c_float work_Atdelta_y[698];
extern c_float work_delta_x[698];
extern c_float work_Pdelta_x[698];
extern c_float work_Adelta_x[1010];
extern c_float work_D_temp[698];
extern c_float work_D_temp_A[698];
extern c_float work_E_temp[1010];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
