#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Python on September 11, 2021 at 18:52:26.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[958];
extern c_float ldata[1270];
extern c_float udata[1270];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[958];
extern c_float Dinvscaling[958];
extern c_float Escaling[1270];
extern c_float Einvscaling[1270];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[2228];
extern c_int linsys_solver_P[2228];
extern c_float linsys_solver_bp[2228];
extern c_float linsys_solver_sol[2228];
extern c_float linsys_solver_rho_inv_vec[1270];
extern c_int linsys_solver_Pdiag_idx[204];
extern csc linsys_solver_KKT;
extern c_int linsys_solver_PtoKKT[204];
extern c_int linsys_solver_AtoKKT[31795];
extern c_int linsys_solver_rhotoKKT[1270];
extern QDLDL_float linsys_solver_D[2228];
extern QDLDL_int linsys_solver_etree[2228];
extern QDLDL_int linsys_solver_Lnz[2228];
extern QDLDL_int   linsys_solver_iwork[6684];
extern QDLDL_bool  linsys_solver_bwork[2228];
extern QDLDL_float linsys_solver_fwork[2228];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[958];
extern c_float ysolution[1270];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[1270];
extern c_float work_rho_inv_vec[1270];
extern c_int work_constr_type[1270];
extern c_float work_x[958];
extern c_float work_y[1270];
extern c_float work_z[1270];
extern c_float work_xz_tilde[2228];
extern c_float work_x_prev[958];
extern c_float work_z_prev[1270];
extern c_float work_Ax[1270];
extern c_float work_Px[958];
extern c_float work_Aty[958];
extern c_float work_delta_y[1270];
extern c_float work_Atdelta_y[958];
extern c_float work_delta_x[958];
extern c_float work_Pdelta_x[958];
extern c_float work_Adelta_x[1270];
extern c_float work_D_temp[958];
extern c_float work_D_temp_A[958];
extern c_float work_E_temp[1270];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
